name: CDRL feedback

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Preparar Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Preparar proyecto
        run: make setup

      - name: Verificar proyecto
        run: make verify